---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ecos-client-cloud-v1
  namespace: ecos
  labels:
    app: ecos-client-cloud-v1
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecos-client-cloud-v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecos-client-cloud-v1
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.244.3.102\"]"
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-hobwav
          persistentVolumeClaim:
            claimName: ecos-client-storage
      containers:
        - name: ecos-client-pod
          image: 'harbor.sums.top/ecos/ecos-client:SNAPSHOT-latest'
          command:
            - tail
            - '-f'
          args:
            - /dev/null
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-hobwav
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor-sums-top
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
